service: hey
image: daodao97/kamal-test
servers:
  - 104.194.87.196
registry:
  server: ghcr.io
  username: daodao97
  password:
    - DOCKER_PASSWORD

proxy:
  ssl: true
  host: kamal.chatbee.cc
  app_port: 8001
  healthcheck:
    interval: 3
    path: /ping
    timeout: 3

ssh:
  user: root
  port: 25022
  keys:
    - ~/.ssh/id_rsa

builder:
  arch: amd64

accessories:
  redis:
    image: redis:7.2
    roles:
      - web
    port: 6379
    volumes:
      - /var/lib/redis:/data